/**
 * Which files in a pull request nobody wrote.
 *
 * A lockfile with four thousand changed lines is not a review; it is the
 * evidence that a review happened somewhere else. Same for minified bundles,
 * protobuf stubs and snapshot files. They belong in the pull request — a
 * lockfile that did *not* change when `package.json` did is worth noticing —
 * but their contents are not read line by line, and a hundred of their lines
 * between two files that were written by hand is how a real change gets
 * skimmed.
 *
 * **GitHub does not answer this over any API.** `PullRequestChangedFile` is
 * `path additions deletions changeType viewerViewedState` and nothing else, and
 * the REST files endpoint carries no more. The web UI's folded "load diff" is
 * decided server-side by Linguist and never leaves the server. So the verdict
 * has to be reached here, from two sources:
 *
 * - **What the repository says.** Linguist reads `linguist-generated` out of
 *   `.gitattributes`, and a repository that has bothered to declare its own
 *   generated files is more reliable than any guess. Parsed by
 *   {@link parseGitAttributes}, and it wins both ways — a path marked
 *   `-linguist-generated` is *not* generated here even if it matches every
 *   pattern below.
 * - **What the path says.** {@link GENERATED_PATTERNS}, when the repository
 *   said nothing.
 *
 * What this deliberately does not do is read file contents. Linguist's other
 * half inspects the bytes — a `// Code generated by` header, a first line that
 * is 30,000 characters of minified JavaScript — and doing that here would mean
 * fetching every file in the pull request to decide whether to show its diff,
 * which is a great deal of traffic to save some scrolling. The cost of missing
 * one is that its diff is shown, which is what happens today anyway.
 *
 * Pure by contract: no DOM, no `chrome.*`, no transport.
 */

import { isNoise } from './filters';

/**
 * Paths whose contents are produced by a tool, by convention.
 *
 * Conservative on purpose, and the bias is not symmetrical. A file wrongly
 * called generated has its diff folded away with a label saying why and an
 * expander next to it; a file wrongly called hand-written costs nothing but the
 * scrolling this feature was meant to save. So a pattern earns its place by
 * being one nobody edits by hand — `build/**` is absent for exactly that
 * reason, since plenty of repositories keep written source in one.
 *
 * Informed by Linguist rather than copied from it: the parts of that list which
 * are decidable from a path are here, and the parts that need the file's bytes
 * are not reachable. See the note above.
 */
export const GENERATED_PATTERNS = [
  // Dependency locks. The largest diffs in most pull requests, and the ones
  // nobody reads: the review is of the manifest that caused them.
  '**/*.lock',
  '**/package-lock.json',
  '**/npm-shrinkwrap.json',
  '**/yarn.lock',
  '**/pnpm-lock.yaml',
  '**/bun.lockb',
  '**/Gemfile.lock',
  '**/Cargo.lock',
  '**/composer.lock',
  '**/poetry.lock',
  '**/Pipfile.lock',
  '**/flake.lock',
  '**/go.sum',

  // Build output that is checked in.
  '**/*.min.js',
  '**/*.min.css',
  '**/*.map',

  // Interface compilers. The `.proto` beside them is the file to review.
  '**/*.pb.go',
  '**/*.pb.cc',
  '**/*.pb.h',
  '**/*.pb.swift',
  '**/*_pb2.py',
  '**/*_pb2_grpc.py',
  '**/*_pb.js',
  '**/*_pb.rb',

  // Code generators that write beside their source.
  '**/*.designer.cs',
  '**/*.g.cs',
  '**/*.g.dart',
  '**/*.freezed.dart',

  // Test snapshots: written by the test run, reviewed by reading the test.
  '**/__snapshots__/**',
  '**/*.snap',

  // Trees that are wholly someone else's or wholly a tool's.
  'vendor/**',
  '**/vendor/**',
  'dist/**',
  '**/dist/**',
  'node_modules/**',
  '**/node_modules/**',
  '**/generated/**',
  '**/__generated__/**',
];

/**
 * One `.gitattributes` line that had something to say about being generated.
 *
 * Ordered, because git resolves a path against every line and the **last**
 * match wins. A repository that marks `**` generated and then exempts one
 * directory depends on that, and a first-match walk would read it backwards.
 */
export interface GeneratedRule {
  /** The pattern, translated to the glob dialect `isNoise` understands. */
  globs: readonly string[];
  /** What the line asserted: `linguist-generated` or `-linguist-generated`. */
  generated: boolean;
}

/** Nothing declared. Distinct from "declared nothing generated". */
export const NO_ATTRIBUTES: readonly GeneratedRule[] = [];

/**
 * A `.gitattributes` pattern, as one or more globs.
 *
 * Git's pattern language and the one `isNoise` compiles differ in exactly the
 * ways that matter here, so the translation is explicit rather than hopeful:
 *
 * - A pattern with no slash in it matches **at any depth**. `*.min.js` is meant
 *   to catch `web/static/app.min.js`, and compiled as written it would only
 *   catch one at the root.
 * - A leading slash anchors to the repository root and is otherwise noise.
 * - A trailing slash names a directory, which means everything beneath it.
 * - A plain name with no wildcard could be either a file or a directory, and
 *   git cannot tell from the pattern either. Both readings are emitted.
 */
export function attributeGlobs(pattern: string): string[] {
  let glob = pattern.trim();
  if (glob === '') return [];

  const anchored = glob.startsWith('/');
  if (anchored) glob = glob.slice(1);

  const directory = glob.endsWith('/');
  if (directory) glob = glob.slice(0, -1);
  if (glob === '') return [];

  // Asked before the `**/` below, which would otherwise answer its own
  // question: every pattern would look like it had a wildcard in it.
  const describes = glob.includes('*') || glob.includes('?');

  // Any depth, unless the pattern said where. A slash anywhere in it — not
  // only at the front — is git's signal that the path is being spelled out.
  if (!anchored && !glob.includes('/')) glob = `**/${glob}`;

  if (directory) return [`${glob}/**`];
  // No wildcard, so this names something rather than describing it — and a
  // name is a file or a directory, with nothing in the pattern to say which.
  if (!describes) return [glob, `${glob}/**`];
  return [glob];
}

/**
 * The `linguist-generated` lines of a `.gitattributes`, in file order.
 *
 * Everything else in the file is skipped rather than understood. `text=auto`,
 * `linguist-vendored`, `merge=ours`, `diff=lfs` and the rest are real and
 * common and say nothing about this question, and a parser that tried to model
 * them would have far more to get wrong.
 *
 * Macro definitions — `[attr]binary -diff -merge -text` — are skipped for the
 * same reason plus one more: expanding them would mean a second pass, and a
 * macro that resolves to `linguist-generated` is rare enough that being wrong
 * about it costs one folded diff.
 */
export function parseGitAttributes(text: string): GeneratedRule[] {
  const rules: GeneratedRule[] = [];

  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (line === '' || line.startsWith('#') || line.startsWith('[attr]')) continue;

    // Split on runs of whitespace. Git allows quoted patterns containing
    // spaces; a path with a space in it that is also declared generated is not
    // a case worth a quoting parser, and the pattern simply fails to match.
    const parts = line.split(/\s+/);
    const pattern = parts[0];
    if (pattern === undefined) continue;

    let generated: boolean | null = null;
    for (const attribute of parts.slice(1)) {
      if (attribute === 'linguist-generated' || attribute === 'linguist-generated=true') {
        generated = true;
      } else if (
        attribute === '-linguist-generated' ||
        attribute === 'linguist-generated=false'
      ) {
        generated = false;
      }
    }
    if (generated === null) continue;

    const globs = attributeGlobs(pattern);
    if (globs.length > 0) rules.push({ globs, generated });
  }

  return rules;
}

/**
 * Whether this file's diff is worth folding away by default.
 *
 * The repository's own answer first, and it is taken whichever way it points:
 * a path the repository marks `-linguist-generated` is shown even if it is
 * called `yarn.lock`, because somebody went out of their way to say so.
 *
 * Only when the repository said nothing at all about a path do the built-in
 * patterns get a say.
 */
export function isGenerated(path: string, rules: readonly GeneratedRule[]): boolean {
  // Backwards, because the last matching line wins and this is the cheapest
  // way to find it.
  for (let at = rules.length - 1; at >= 0; at -= 1) {
    const rule = rules[at];
    if (rule !== undefined && isNoise(path, rule.globs)) return rule.generated;
  }

  return isNoise(path, GENERATED_PATTERNS);
}
