/**
 * The check that makes a generated mapping safe to commit.
 *
 * `lib/icons/material.ts` is 268 kilobytes nobody will read, so the only thing
 * standing between it and quiet staleness is something that fails when it has
 * fallen behind the package it came from. Bumping `material-icon-theme` and
 * forgetting `npm run file-icons` would otherwise ship a build whose mapping
 * names drawings that are no longer in `public/file-icons` — a rail of broken
 * images, on whichever file types happened to move.
 *
 * The drawings are checked too, and for the sharper reason: they are fetched
 * by `<img src>`, so a name in the table with no file behind it is not a
 * fallback, it is a hole. It stays silent until somebody opens a pull request
 * containing exactly that kind of file.
 */

import { readdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { MATERIAL_ICONS } from './material';
import { DEFAULT_FILE, DEFAULT_FOLDER, OPEN_SUFFIX, fileIcon, folderIcon } from './lookup';

const require = createRequire(import.meta.url);

/**
 * The installed package, read the way the generator reads it.
 *
 * A devDependency, so this import exists at test time and in no build output.
 */
const theme = require('material-icon-theme/dist/material-icons.json') as {
  file: string;
  folder: string;
  folderExpanded: string;
  fileExtensions: Record<string, string>;
  fileNames: Record<string, string>;
  folderNames: Record<string, string>;
  folderNamesExpanded: Record<string, string>;
  light?: Partial<Record<'fileExtensions' | 'fileNames' | 'folderNames', Record<string, string>>>;
};

/** Repository-relative, which is what `process.cwd()` is under vitest. */
const drawings = new Set(
  readdirSync(path.join(process.cwd(), 'public', 'file-icons')).map((file) =>
    file.replace(/\.svg$/, ''),
  ),
);

const TABLES = ['fileExtensions', 'fileNames', 'folderNames'] as const;

describe('the generated mapping', () => {
  it.each(TABLES)('is what the installed theme says about %s', (table) => {
    expect(
      MATERIAL_ICONS[table],
      `${table} is stale: run \`npm run file-icons\``,
    ).toEqual(theme[table]);
  });

  it.each(TABLES)('carries the theme’s light overrides for %s', (table) => {
    expect(MATERIAL_ICONS.light?.[table] ?? {}).toEqual(theme.light?.[table] ?? {});
  });

  it('leaves out the expanded folder table, because every row of it is derivable', () => {
    // The generator refuses to run when this stops being true. Asserting it
    // here as well is what makes the absence above a decision rather than an
    // omission — and what catches a `material.ts` generated by an older
    // script against a newer package.
    for (const [name, icon] of Object.entries(theme.folderNames)) {
      expect(theme.folderNamesExpanded[name], name).toBe(`${icon}${OPEN_SUFFIX}`);
    }
  });

  it('agrees with the theme about what an unrecognised file and folder get', () => {
    expect(theme.file).toBe(DEFAULT_FILE);
    expect(theme.folder).toBe(DEFAULT_FOLDER);
    expect(theme.folderExpanded).toBe(`${DEFAULT_FOLDER}${OPEN_SUFFIX}`);
  });
});

describe('the drawings behind it', () => {
  it('has a file for every icon the tables can name', () => {
    const named = new Set([DEFAULT_FILE, DEFAULT_FOLDER]);
    for (const table of TABLES) {
      for (const icon of Object.values(MATERIAL_ICONS[table])) named.add(icon);
      for (const icon of Object.values(MATERIAL_ICONS.light?.[table] ?? {})) named.add(icon);
    }

    expect([...named].filter((icon) => !drawings.has(icon))).toEqual([]);
  });

  it('has a file for every folder icon opened, which no table names', () => {
    // The derived half. `folderIcon` appends `-open` and nothing in the
    // mapping mentions the result, so this is the only thing that would catch
    // a missing one.
    const opened = new Set([`${DEFAULT_FOLDER}${OPEN_SUFFIX}`]);
    for (const icon of Object.values(MATERIAL_ICONS.folderNames)) {
      opened.add(`${icon}${OPEN_SUFFIX}`);
    }
    for (const icon of Object.values(MATERIAL_ICONS.light?.folderNames ?? {})) {
      opened.add(`${icon}${OPEN_SUFFIX}`);
    }

    expect([...opened].filter((icon) => !drawings.has(icon))).toEqual([]);
  });

  it('ships nothing the tables cannot reach', () => {
    // The other direction, so a theme that drops an icon does not leave its
    // drawing in the extension for the store to review and nobody to see.
    const reachable = new Set([DEFAULT_FILE]);
    for (const table of TABLES) {
      for (const icon of Object.values(MATERIAL_ICONS[table])) reachable.add(icon);
      for (const icon of Object.values(MATERIAL_ICONS.light?.[table] ?? {})) reachable.add(icon);
    }
    for (const icon of [...reachable]) {
      if (icon.startsWith('folder') && !icon.endsWith(OPEN_SUFFIX)) {
        reachable.add(`${icon}${OPEN_SUFFIX}`);
      }
    }
    reachable.add(DEFAULT_FOLDER);
    reachable.add(`${DEFAULT_FOLDER}${OPEN_SUFFIX}`);

    expect([...drawings].filter((icon) => !reachable.has(icon))).toEqual([]);
  });
});

describe('what the rail will actually draw', () => {
  // Spot checks through the real tables, so a mapping that loaded but points
  // somewhere useless has something to fail against.
  it('knows the languages this repository is written in', () => {
    expect(fileIcon('ui/FileTree.tsx', MATERIAL_ICONS, 'dark')).toBe('react_ts');
    expect(fileIcon('lib/icons/lookup.ts', MATERIAL_ICONS, 'dark')).toBe('typescript');
    expect(fileIcon('package.json', MATERIAL_ICONS, 'dark')).toBe('nodejs');
    expect(fileIcon('entrypoints/review/style.css', MATERIAL_ICONS, 'dark')).toBe('css');
  });

  it('knows a readme from the Markdown around it', () => {
    expect(fileIcon('README.md', MATERIAL_ICONS, 'dark')).toBe('readme');
    expect(fileIcon('DESIGN.md', MATERIAL_ICONS, 'dark')).toBe('markdown');
  });

  it('draws a folder it has never heard of as a folder', () => {
    // Deliberately nonsense. The theme knows 4,654 folder names — `widgets`
    // and `components` among them — so a plausible-sounding one would be
    // testing the table rather than the fallback.
    expect(folderIcon('frobnicator/', false, MATERIAL_ICONS, 'dark')).toBe(DEFAULT_FOLDER);
    expect(folderIcon('frobnicator/', true, MATERIAL_ICONS, 'dark')).toBe(
      `${DEFAULT_FOLDER}${OPEN_SUFFIX}`,
    );
  });

  it('draws a file it has never heard of as a file', () => {
    expect(fileIcon('notes.qqq', MATERIAL_ICONS, 'dark')).toBe(DEFAULT_FILE);
  });
});
